spring.application.name=CodePilot
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://localhost:5332/postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
