spring.application.name=CodePilot-backend
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
codepilot.agentcore.runtime-arn=${RUNTIME_ARN}
codepilot.agentcore.region=${AWS_REGION}
spring.codepilot.ai.base-url=${AI_BASE_URL}